In [1]:

import tensorflow as tf

import numpy as np

In [2]:
tf.reset_default_graph()
h_dec = tf.ones([100, 256])
w=tf.get_variable("w", [h_dec.get_shape()[1], 5]) 
b=tf.get_variable("b", [5], initializer=tf.constant_initializer(0.0))
results=tf.matmul(h_dec,w)+b

In [3]:
sess=tf.InteractiveSession()
tf.global_variables_initializer().run()
print(results.eval())
print(h_dec.eval())
print(w.eval())
print(b.eval())
sess.close()

[[-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33943987]
 [-0.82228386 -0.42327192 -1.5493524  -1.2462984   0.33